import Link from "next/link";
import { notFound } from "next/navigation";
import { Calendar, ChevronLeft, MapPin, PawPrint, Star } from "lucide-react";
import { hotels as hotelsApi } from "@/lib/api";
import { formatUsd } from "@/lib/utils";
import { EcoScoreDetail } from "@/components/eco/EcoScoreDetail";
import { PartnerMapSection } from "@/components/partners/PartnerMapSection";

export const dynamic = "force-dynamic";

interface PageProps {
  params: Promise<{ id: string }>;
}

export default async function HotelDetailPage({
  params,
}: PageProps): Promise<React.ReactElement> {
  const { id } = await params;
  const [hotel, eco] = await Promise.all([
    hotelsApi.get(id).catch(() => null),
    hotelsApi.ecoScore(id).catch(() => null),
  ]);

  if (!hotel) notFound();

  return (
    <div className="bg-[var(--color-bonvoy-mist)]">
      {/* Hero */}
      <section
        className="relative h-[420px] md:h-[520px] bg-cover bg-center"
        style={{ backgroundImage: `url(${hotel.image_url})` }}
        aria-hidden
      >
        <div className="absolute inset-0 bg-gradient-to-t from-black/65 via-black/20 to-transparent" />
        <div className="absolute inset-x-0 top-4">
          <div className="mx-auto max-w-[1280px] px-6">
            <Link
              href="/search"
              className="inline-flex items-center gap-1 text-white/85 hover:text-white text-[13px]"
            >
              <ChevronLeft size={16} /> Back to results
            </Link>
          </div>
        </div>
        <div className="absolute inset-x-0 bottom-0">
          <div className="mx-auto max-w-[1280px] px-6 pb-8 text-white">
            <p className="text-[11px] uppercase tracking-[0.22em] text-white/85 mb-2">
              {hotel.brand}
            </p>
            <h1 className="heading-display text-3xl md:text-5xl mb-2 max-w-3xl drop-shadow-sm">
              {hotel.name}
            </h1>
            <div className="flex flex-wrap items-center gap-x-5 gap-y-2 text-[14px] text-white/95">
              <span className="inline-flex items-center gap-1">
                <MapPin size={14} />
                {hotel.address}
              </span>
              <span className="inline-flex items-center gap-1">
                <Star size={14} className="fill-white" />
                {hotel.rating.toFixed(1)}
              </span>
              {hotel.pet_friendly && (
                <span className="inline-flex items-center gap-1">
                  <PawPrint size={14} />
                  Pet-friendly
                </span>
              )}
            </div>
          </div>
        </div>
      </section>

      <div className="mx-auto max-w-[1280px] px-6 py-10 grid grid-cols-1 lg:grid-cols-[1fr_360px] gap-8">
        <div className="space-y-8 min-w-0">
          {/* Editorial */}
          <section className="bg-white border border-[var(--color-bonvoy-rule)] rounded-lg p-6">
            <p className="text-[15px] text-[var(--color-bonvoy-ink)] leading-relaxed mb-4">
              {hotel.content.editorial}
            </p>
            <ul className="grid grid-cols-1 sm:grid-cols-2 gap-x-6 gap-y-2 text-[13px] text-[var(--color-bonvoy-muted)]">
              {hotel.content.highlights.map((h) => (
                <li key={h} className="flex gap-2">
                  <span className="text-[var(--color-marriott-red)]">·</span>
                  {h}
                </li>
              ))}
            </ul>
            <p className="mt-4 text-[11px] uppercase tracking-[0.16em] text-[var(--color-bonvoy-muted)]">
              Generated by {hotel.content.generated_by === "litellm" ? "TIP.AI" : "mock LLM"}
            </p>
          </section>

          {/* Eco breakdown — hero feature */}
          {eco && <EcoScoreDetail data={eco} />}

          {/* Pet info if applicable */}
          {hotel.pet_friendly && (
            <section className="bg-white border border-[var(--color-bonvoy-rule)] rounded-lg p-6">
              <p className="text-[11px] uppercase tracking-[0.18em] text-[var(--color-marriott-red)] mb-1">
                Traveling with pets
              </p>
              <h3 className="text-[20px] font-medium text-[var(--color-bonvoy-ink)] mb-2">
                Pet policy at {hotel.name.split(",")[0]}
              </h3>
              <p className="text-[14px] text-[var(--color-bonvoy-ink)] mb-3">
                {hotel.pet_note ?? "Pets welcome with prior arrangement."}
              </p>
              <div className="flex flex-wrap gap-x-6 gap-y-2 text-[13px] text-[var(--color-bonvoy-muted)]">
                {hotel.pet_max_weight_kg != null && (
                  <span>Max weight: {hotel.pet_max_weight_kg} kg</span>
                )}
                {hotel.pet_fee_usd != null && (
                  <span>Pet fee: {formatUsd(hotel.pet_fee_usd)} per stay</span>
                )}
              </div>
            </section>
          )}

          {/* Partner map — hero feature */}
          <PartnerMapSection hotel={hotel} />

          {/* Community events */}
          {hotel.community_events.length > 0 && (
            <section className="bg-white border border-[var(--color-bonvoy-rule)] rounded-lg p-6">
              <p className="text-[11px] uppercase tracking-[0.18em] text-[var(--color-marriott-red)] mb-1">
                On property
              </p>
              <h3 className="text-[20px] font-medium text-[var(--color-bonvoy-ink)] mb-4">
                Community events
              </h3>
              <ul className="space-y-3">
                {hotel.community_events.map((ev, i) => (
                  <li
                    key={i}
                    className="grid grid-cols-[auto_1fr_auto] items-center gap-4 py-2 border-b border-[var(--color-bonvoy-rule)] last:border-b-0"
                  >
                    <Calendar size={16} className="text-[var(--color-bonvoy-muted)]" />
                    <span className="text-[14px] text-[var(--color-bonvoy-ink)]">
                      {String(ev.name)}
                      <span className="block text-[12px] text-[var(--color-bonvoy-muted)]">
                        {String(ev.location)}
                      </span>
                    </span>
                    <span className="text-[12px] text-[var(--color-bonvoy-muted)] text-right">
                      {String(ev.time)}
                    </span>
                  </li>
                ))}
              </ul>
            </section>
          )}
        </div>

        {/* Booking rail */}
        <aside className="lg:sticky lg:top-32 lg:self-start space-y-4">
          <div className="bg-white border border-[var(--color-bonvoy-rule)] rounded-lg p-6">
            <p className="text-[11px] uppercase tracking-[0.18em] text-[var(--color-bonvoy-muted)]">
              From
            </p>
            <p className="text-[32px] font-medium text-[var(--color-bonvoy-ink)] leading-tight">
              {formatUsd(hotel.price_per_night)}
              <span className="text-[13px] font-normal text-[var(--color-bonvoy-muted)]">
                {" "}
                / night
              </span>
            </p>
            <p className="text-[12px] text-[var(--color-bonvoy-muted)] mb-4">
              Mock pricing · taxes &amp; fees not shown.
            </p>

            <p className="text-[12px] uppercase tracking-[0.16em] text-[var(--color-bonvoy-muted)] mb-2">
              Available rooms
            </p>
            <ul className="space-y-2 mb-5">
              {hotel.content.room_types.map((rt) => (
                <li
                  key={rt}
                  className="border border-[var(--color-bonvoy-rule)] rounded-md px-3 py-2 text-[13px] flex items-center justify-between"
                >
                  <span>{rt}</span>
                  <span className="text-[12px] text-[var(--color-bonvoy-muted)]">
                    {formatUsd(hotel.price_per_night)}
                  </span>
                </li>
              ))}
            </ul>

            <button
              type="button"
              className="w-full rounded-full bg-[var(--color-marriott-red)] hover:bg-[var(--color-marriott-red-dark)] text-white py-3 text-[14px] font-medium"
            >
              Reserve room (demo)
            </button>
            <p className="mt-2 text-[11px] text-[var(--color-bonvoy-muted)] text-center">
              Booking is disabled in this prototype.
            </p>
          </div>

          {eco && (
            <div className="bg-[var(--color-bonvoy-ink)] text-white rounded-lg p-5">
              <p className="text-[11px] uppercase tracking-[0.18em] text-white/70 mb-1">
                Why this matters
              </p>
              <p className="text-[13px] leading-relaxed text-white/90">
                Booking eco-leading hotels rewards you with{" "}
                <span className="font-medium text-white">
                  {eco.green_points_multiplier.toFixed(1)}× Bonvoy Green Points
                </span>{" "}
                — and signals demand for sustainable hospitality across the
                portfolio.
              </p>
            </div>
          )}
        </aside>
      </div>
    </div>
  );
}
